### ISSUE TITLE
Provision Script wget should have --content-disposition flag

### ISSUE THREAD

**Issue by gymdreams8** [ai-dock/stable-diffusion-webui#1]
For checkpoints, `wget` need to add `--content-disposition` flag, otherwise the files won’t be saved correctly.

Many Civitai download links don’t have the the filename in the URL, so this flag is required.

Example:

```sh
CHECKPOINT_MODELS=(\
    "https://civitai.com/api/download/models/181248?type=Model&format=SafeTensor&size=pruned&fp=fp16" 
)
```
currently will be saved in the folder as this:

```sh
$ ls
'181248?type=Model&format=SafeTensor&size=pruned&fp=fp16'
```

but if instead you `wget` with the flag:

```sh
cd /workspace/stable-diffusion-webui/models/Stable-diffusion
wget 'https://civitai.com/api/download/models/181248?type=Model&format=SafeTensor&size=pruned&fp=fp16' --content-disposition
```
then it will be saved correctly as: `virileReality_v30BETA3.safetensors`

**Comment by robballantyne** [comment]
Fixed by #2b56a0f

**Comment by robballantyne** [comment]
Fixed. Thank you @gymdreams8

**Comment by gymdreams8** [comment]
Awesome. closing 🥰
