### ISSUE TITLE
Can't load newly created textual embedding .pt file

### ISSUE THREAD

**Issue by iolmstead23** [ai-dock/stable-diffusion-webui#10]
As the title states whenever I create a new textual inversion embedding the file is created, but when I attempt to load the embedding into my training tab it gives me an error. I have tried disabling extra extensions and that did not solve the issue. I can train/use embeddings just fine if I use --disable-safe-unpickling but this is a bandaid fix. ChatGPT isn't very helpful on the subject and I am led to think this is either a setting that is incorrectly set or its an underlying bug with the version of pytorch installed.

I am renting a RTX 4090 from Vast.ai. I am using Python 3.10.13 with Pytorch version 2.1.1. I am using the same versions to run on my local machine which works fine safely pickling and unpickling.

```
*** Error verifying pickled file from /opt/stable-diffusion-webui/embeddings/[Redacted]
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "/opt/stable-diffusion-webui/modules/safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "/opt/stable-diffusion-webui/modules/safe.py", line 84, in check_pt
        check_zip_filenames(filename, z.namelist())
      File "/opt/stable-diffusion-webui/modules/safe.py", line 76, in check_zip_filenames
        raise Exception(f"bad file inside {filename}: {name}")
    Exception: bad file inside /opt/stable-diffusion-webui/embeddings/[Redacted]: [Redacted]/byteorder
---
*** Error loading embedding [Redacted]
    Traceback (most recent call last):
      File "/opt/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 203, in load_from_dir
        self.load_from_file(fullfn, fn)
      File "/opt/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 184, in load_from_file
        embedding = create_embedding_from_data(data, name, filename=filename, filepath=path)
      File "/opt/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 284, in create_embedding_from_data
        if 'string_to_param' in data:  # textual inversion embeddings
    TypeError: argument of type 'NoneType' is not iterable
---
```

**Comment by robballantyne** [comment]
The image is due for a rebuild onto PyTorch 2.2.0 which will hopefully resolve the issue. 

Should be done today or tomorrow. A lot of changes have gone into the base images which is why I've been unable to track the latest PyTorch but that shouldn't be an issue now.

If the version upgrade doesn't help I can investigate further

**Comment by iolmstead23** [comment]
Awesome! I will test out the pytorch today and let you know the results. Thank you!

**Comment by iolmstead23** [comment]
I am getting this error although it does not give me an error when I create the embedding. The file appears to be created, but cannot be read.

```
*** Error verifying pickled file from /opt/stable-diffusion-webui/embeddings/[Redacted]
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "/opt/stable-diffusion-webui/modules/safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "/opt/stable-diffusion-webui/modules/safe.py", line 84, in check_pt
        check_zip_filenames(filename, z.namelist())
      File "/opt/stable-diffusion-webui/modules/safe.py", line 76, in check_zip_filenames
        raise Exception(f"bad file inside {filename}: {name}")
    Exception: bad file inside /opt/stable-diffusion-webui/embeddings/Test.pt: Test/byteorder
---
*** Error loading embedding [Redacted]
    Traceback (most recent call last):
      File "/opt/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 203, in load_from_dir
        self.load_from_file(fullfn, fn)
      File "/opt/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 184, in load_from_file
        embedding = create_embedding_from_data(data, name, filename=filename, filepath=path)
      File "/opt/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 284, in create_embedding_from_data
        if 'string_to_param' in data:  # textual inversion embeddings
    TypeError: argument of type 'NoneType' is not iterable
---
```

**Comment by robballantyne** [comment]
@iolmstead23 can you try adding `--disable-safe-unpickle` to the environment variable `WEBUI_FLAGS`?

This should hopefully resolve the problem

**Comment by iolmstead23** [comment]
Yes I mentioned using --disable-safe-unpickle WEBUI flag in my original post, but a lot of others are not willing to do this. This means that my embeddings will only be accessible to those who turn off their safety features.

I did some investigating and found a user that is saying there is another error they are getting. I think there might be an issue with the pickle files because when I open the embedding in 7zip it shows the files are packaged, but still A1111 cannot read them. It it showing the Data as NoneType. This is obviously untrue as the file loads fine when safety is disabled.

```
"*** Error loading embedding Marilyn_Monroe_[TI.pt](http://ti.pt/)

Traceback (most recent call last):

File "E:\Tools\stable-diffusion-webui\modules\textual_inversion\textual_[inversion.py](http://inversion.py/)", line 203, in load_from_dir

self.load_from_file(fullfn, fn)

File "E:\Tools\stable-diffusion-webui\modules\textual_inversion\textual_[inversion.py](http://inversion.py/)", line 184, in load_from_file

embedding = create_embedding_from_data(data, name, filename=filename, filepath=path)

File "E:\Tools\stable-diffusion-webui\modules\textual_inversion\textual_[inversion.py](http://inversion.py/)", line 284, in create_embedding_from_data

if 'string_to_param' in data: # textual inversion embeddings

TypeError: argument of type 'NoneType' is not iterable"
```

**Comment by iolmstead23** [comment]
I made progress! If you delete .data folder and byteorder from the embedding it loads fine! The safety check looks at the files inside the pt file and verifies if it fits its description. Byteorder and .data/serlization_id are not recognized as files it can accept so it throws an error.

Somehow when A1111 attempts to create a .pt file it packages byteorder and .data/serilization_id which is where the error exists.

**Comment by robballantyne** [comment]
I'm glad you figured that out, I would have got there but not as quickly as you.  Looks like it's not an issue in my distribution though so are we safe to close?

**Comment by robballantyne** [comment]
@iolmstead23 You can replace the latest tag with [jupyter-pytorch-2.1.1-py3.10-cuda-11.8.0-runtime-22.04](https://github.com/ai-dock/stable-diffusion-webui/pkgs/container/stable-diffusion-webui/181905910?tag=jupyter-pytorch-2.1.1-py3.10-cuda-11.8.0-runtime-22.04)

I always build against at least 3 previous torch versions in case of problems. Hopefully this will help.

**Comment by iolmstead23** [comment]
I have confirmed both running torch 2.1.1 and setting _use_new_zipfile_serialization to False did not fix the issue. _use_new_zipfile_serialization needs to be set to true so I can open the files in 7zip which tells me that is not the issue why extra files are being created inside the pt file.
