### ISSUE TITLE
Error running on vultr? Or what am i doing wrong??

### ISSUE THREAD

**Issue by bpawnzZ** [ai-dock/stable-diffusion-webui#11]
I build and all goes fine.  but when i try to docker-compose up  this i get the following error.  Torch is installed and nvidia-smi shows that my drivers are good?  Web-Ui runs for about 5 seconds and shuts down and enters a loop doing this until i stop it.  I am able to get to port 1111 but cannot connect to web-ui.  Any suggestions?  Thanks!!

RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by robballantyne** [comment]
You'll need the Nvidia container toolkit installed on the VM for the GPU to be available to docker.

The compose file will also need the Nvidia devices section uncommentiing

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html should have everything you need to get it up and running

**Comment by bpawnzZ** [comment]
That is not the issue.  I have nvidia toolkit installed inside of Vultr.  And i tried testing it on a Desktop that has stable diffusion working inside of docker already and and I am having the same issues.  Basically webui starts and then crashes.  When i check services on ip:1111  Jupyter and webui fail.  I am really at a loss currently.  Tried to do a clean rebuild and same errors.  so nothing to do with anything I initially added.  Also have tried to compile on more than one machine.  Same errors.

**Comment by robballantyne** [comment]
Cannot reproduce
