### ISSUE TITLE
WebUI Forge?

### ISSUE THREAD

**Issue by WhiteMemory99** [ai-dock/stable-diffusion-webui#13]
I've been using your images for a long time and enjoy them, but I'd also love to see [WebUI Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) images from you. This shouldn't be a huge issue or hard to maintain since the two are mostly compatible.

**Comment by robballantyne** [comment]
I'll add it, but I have quite a few to do.  I have been asked for invoke and sd.next plus I am spending quite a lot of time making sure my desktop image is working properly,  I will definitely get to it though and I should get quicker soon now that I'm happy with the base images.
