### ISSUE TITLE
A111 Extension: Use Reactor in place of ROOP

### ISSUE THREAD

**Issue by gymdreams8** [ai-dock/stable-diffusion-webui#2]
The ROOP extension that you’re using right now is the original implementation of ROOP: https://github.com/s0md3v/sd-webui-roop

But it has limitations. Specifically, it has NSFW detection, which is not an issue in and by itself, except that all of these libraries could give false positives. The issue with false positives is obvious — you render an image that’s SFW, but it prevents you from rendering regardless. In some ways, for web applications such as Replicate (which uses a different Python library), the false positives may be required (though I could also show you hilarious examples of it which shows just how ridiculous some of these false positives are). Since this is an end-user image, I feel like that having these restrictions is unnecessary.

There’s a fork of that removes this limitation: https://github.com/Gourieff/sd-webui-reactor — originally, that was the only implementation, but now that fork author has added new features to it and so now it’s far superior than the original.

I tried to use it directly in the provision script but I couldn’t get it to run. Maybe you could? I know that this is not supposed to be an “opinionated” docker image, but the main issue with the false positives makes the one you use unsuitable for production use. I hope that you would consider changing it.

Thanks for all the hard work as always!

**Comment by robballantyne** [comment]
Thanks @gymdreams8 I'll change it.

The provisioning script is user replaceable and I'm happy to be guided as to what should be default, and this makes perfect sense.

**Comment by gymdreams8** [comment]
Sure thing — I guess what I’m suggesting would be to provide separate links to your image with sensible defaults:

- barebones / no control net models
- all control net models
- some specific changes to extensions etc

And also that for extensions, I think that if somehow you can include in the command line (can it?) instead of the provisioning script (even though technically they are equal), then it would then allow anyone to just put them a la carte in the command line as copied from a site instead of having to somehow put it in a provisioning.

THAT SAID, I suppose that I could also write that provisioning script as an output from a site — actually that might work perfectly also. I have to think about it. 

Right now, I see myself uploading a script to a public repo and then tweak it. This would be way too geeky for a regular user. If instead they would just be able to copy and paste something from a website (or web ui) into the docker image config then I think that they will do it.

**Comment by robballantyne** [comment]
Quick thought on this:

Maybe something like `apply-config.sh https://some.site/some-config-slug`

Executes 

```
wget -O custom.sh "${1}"
source custom.sh
```

You could host a UI to generate and host a bash script for this.

Effectively the above process is what happens now with the provisioning script, but called directly from init.sh rather than with a userspace command. That's easy to change.

Regarding extensions, do you mean from a terminal, or from the docker run command? If terminal, that's also straightforward as the logic for it is already present in the default provisioning script and could be moved to, for example, get-extension.sh

Let me know what you think

**Comment by gymdreams8** [comment]
Yup I guess that could work. 

> Regarding extensions, do you mean from a terminal, or from the docker run command? If terminal, that's also straightforward as the logic for it is already present in the default provisioning script and could be moved to, for example, get-extension.sh

I just realized that i didn’t type this comment very well. What I meant is to directly include the extensions on the command line.

My main issue right now with the provision script is that it’s not so easy for people to just paste one thing into it (one step) and then not have to do anything extra.

Your solution of 
```sh
wget -O custom.sh "${1}"
source custom.sh
```
SHOULD work provided that they won’t need to modify any part of it. Basically, as soon as you ask a user to “search for text” and “paste this bits only in an area” then they get scared.

If instead they would just paste a full chunk of text into a text box and overwrite everything, then it feels easy and fool-proof — even if the end result is exactly the same. 

It’s a “fear of tech” issue more than anything else.

**Comment by robballantyne** [comment]
I can look to do something like that. I'm re-working the service portal now, so that links, logs and service start/stop controls all appear in a unified interface so there should be room for this.
