### ISSUE TITLE
Vast pre-configured template fails to start

### ISSUE THREAD

**Issue by advanpix** [ai-dock/stable-diffusion-webui#21]
I provide machines on vast.ai for renting. I noticed that any time user tries to use pre-configured template from this repository (as it is): https://link.ai-dock.org/template-vast-sd-webui
It fails with following error (docker container inspect):

```
failed to create task for container: failed to create shim task: OCI runtime create failed: 
runc create failed: unable to start container process: 
exec: \"env | grep _ >> /etc/environment; /opt/ai-dock/bin/init.sh;\": stat env | grep _ >> /etc/environment; /opt/ai-dock/bin/init.sh;: 
no such file or directory: unknown
```

To make it work, the template needs to be changed ("Launch Mode" needs to be changed to "Run a jupyter-python notebook"  instead of "Docker Run: use docker ENTRYPOINT." in "Template Editor"). Any chance the pre-configured template can be modified to have this mode by default?

Or is there some workaround for this issue? I am running Ubuntu 22.04 with the docker:

```
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:23 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:23 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0 

```

**Comment by robballantyne** [comment]
Looks like the link is pointing to an older template version that's got a mix of jupyter and endpoint settings. Will fix this

**Comment by advanpix** [comment]
Thank you for your quick reply! It has been painful to see this happening over and over again. Decided to reach to you here.

**Comment by robballantyne** [comment]
No problem, I'll always deal with issues as quickly as possible, particularly those that cause issues on Vast.

I need to check my email settings though because I didn't get a notification on this one.  I'll keep an eye on the template but please let me know if it causes any more problems.
