### ISSUE TITLE
I have a small problem to download wildcards and config.json

### ISSUE THREAD

**Issue by Ineman** [ai-dock/stable-diffusion-webui#22]
Sorry, it's a beginner question.
I am using vast.ai and noob about code.

I modified provisioning script like this to download wiledcard txt files and config.json file for webui setting.
[https://gist.githubusercontent.com/Ineman/eb6e35efedda1dcf1ec49af89d4ff117/raw](https://gist.githubusercontent.com/Ineman/eb6e35efedda1dcf1ec49af89d4ff117/raw)

then after install complete, file name is crush. 
HAIR.txt become Wildcards%2FHAIR.txt and ui-config.json become config%2Fui-config.json. config.json become config%2Fconfig.json.

But checkpoint and lora files name located in 'workspace/storage/stable_diffusion/models/ckpt/' are not crush.

I need help. Why it happen to me?

![Screenshot_20240620-115414_Chrome](https://github.com/ai-dock/stable-diffusion-webui/assets/91766944/4878befc-be37-4901-baa9-1bd0a6e90839)

**Comment by robballantyne** [comment]
I think this may be because you have a trailing '/' in the target directory.  eg

```
provisioning_get_models \
        "${WORKSPACE}/stable-diffusion-webui/extensions/sd-dynamic-prompts/wildcards/" \
        "${WILDCARD_MODELS[@]}"
``
should be:

```
provisioning_get_models \
        "${WORKSPACE}/stable-diffusion-webui/extensions/sd-dynamic-prompts/wildcards" \
        "${WILDCARD_MODELS[@]}"
```

I'll update the default script soon to handle this situation because it's my error

**Comment by Ineman** [comment]
Thank you, but it doesn't work.
I solved this problem by adding another function in provisioning_start which contains wget command.
