### ISSUE TITLE
Unable to login at latest

### ISSUE THREAD

**Issue by vladfaust** [ai-dock/stable-diffusion-webui#24]
With the `:latest` tag deployed on the same Vast.ai machine I can not get past the login screen; it just redirects back to login with 200 code regardless of the user-password combination. Works flawlessly with `v2-cuda-11.8.0-base-22.04`, though.

**Comment by robballantyne** [comment]
Can you try with this new template https://cloud.vast.ai/?ref_id=62897&template_id=6bd70de216aa40f5bc3ba575795ef3cd

I couldn't reproduce the bug and I was able to use `WEB_USER` and WEB_PASSWORD`

The default username on Vast, if left unset is 'vastai' - Maybe that was the cause.

Also, on Vast you can simply click the open button to access the instance as it uses a token mechanism to log you in
