### ISSUE TITLE
Can't customize embeddings and other things

### ISSUE THREAD

**Issue by knamnguyen** [ai-dock/stable-diffusion-webui#7]
I looked a at the provisioning script and saw no place to define a custom embedding when the template boots up on vast.ai

Preferrably & alternatively, I want to boot the instance, and then sync my models on the cloud to the new instance. I have a copy of the /stable-diffusion-webui/ folder on my gg drive with the exact same structure as the template, including a custom embedding and a custom model. When I try syncing, only the model (epic realisism) comes over, while the embedding folder is still empty (should contain "bad dream" after syncing).

<img width="383" alt="image" src="https://github.com/ai-dock/stable-diffusion-webui/assets/85094695/8843ba37-b597-4fa8-857e-8727c6923584">

<img width="344" alt="image" src="https://github.com/ai-dock/stable-diffusion-webui/assets/85094695/8532bbec-dcbb-457b-b769-b94ff4f1d9b1">

<img width="502" alt="image" src="https://github.com/ai-dock/stable-diffusion-webui/assets/85094695/7f04d0fa-dbda-4d75-8e0d-7e024182e984">

<img width="476" alt="image" src="https://github.com/ai-dock/stable-diffusion-webui/assets/85094695/f9055883-7609-4ce8-aa1b-2c095d1af195">

Please help! Thank you so much

**Comment by robballantyne** [comment]
The provisioning script will take any commands as it's just a bash script; Feel free to override it completely if necessary to achieve what you need
