### ISSUE TITLE
Automatic 1111 WEBUI API returns Error 401 Unauthorized

### ISSUE THREAD

**Issue by MixoMax** [ai-dock/stable-diffusion-webui#8]
When setting --api in the webui startup arguments, the /docs endpoint can be reached, but when trying to send a post request to /sdapi/v1/txt2img, I always get Error 401 Unauthorized. I have a username and password set for web authentication but do not know in which part of the POST request to send it along (propably in the header but what is the exact structure)?

```
API Endpoint: POST http://127.0.0.1:7860/sdapi/v1/txt2img
Header:
{
    "Content-Type": "application/json"
}
Payload:
{
    "prompt": "Astronauts on the moon",
    "guidance_scale": 7,
    "seed": -1,
    "width": 512,
    "height": 512,
    "steps": 20,
    "samples": 1,
    "send_images": true,
    "sampler_index": "Euler"
}

Response: 
401 Unauthorized
```

**Comment by robballantyne** [comment]
Sorry for the late reply. You need to set Authorization headers
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

Currently only Basic is supported but the next update will also permit Bearer

**Comment by robballantyne** [comment]
Both basic and bearer supported
