### ISSUE TITLE
CUDA out of Memory Issue

### ISSUE THREAD

**Issue by richbrownio** [ai-dock/stable-diffusion-webui#9]
Even with a 24GB Nvidia RTX 4090, when trying to run an XL model I'm constantly getting a CUDA out of memory error. Any thoughts on exactly how to fix this? 

OutOfMemoryError: CUDA out of memory. Tried to allocate 1008.00 MiB. GPU 0 has a total capacty of 23.65 GiB of which 927.19 MiB is free. Process 4050195 has 22.73 GiB memory in use. Of the allocated memory 21.74 GiB is allocated by PyTorch, and 537.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by robballantyne** [comment]
https://stackoverflow.com/questions/73747731/runtimeerror-cuda-out-of-memory-how-can-i-set-max-split-size-mb may be a useful start.

Currently you'll need to set the environment variable on instance startup but I'm pushing an update that will allow supervisord to pick up environment changes without a full restart that will help to debug this.

This being said, it should work fine on a 4090. PyTorch is due an update so that might also help. That will be ready today/tomorrow

**Comment by richbrownio** [comment]
Thanks Rob.

**Comment by robballantyne** [comment]
New builds have been pushed and docs updated for new tags. latest now points to PyTorch 2.2.0 CU11.8.0 but there are also builds for Cuda 12.

Hopefully one of these helps but let me know if not.

**Comment by richbrownio** [comment]
Thanks Rob, it didn't help. I still got the same error message when trying to use an SDXL image resolution of 896x1152. I'm also seeing a weird behavior now where when I stop the vast instance, upon restart it relaunched and kicked off the provisioning script instead of just restarting the instance. This sucks as I already downloaded about 10 checkpoints in the original launch and now it's redownloading them all again costing the bandwidth charge for redownload.

**Comment by robballantyne** [comment]
Sorry this hasn't helped Rich, it's late here but I'll have time tomorrow to really dig into this to find out what's going wrong. I'll update here as soon as possible

**Comment by robballantyne** [comment]
Quick update.  I've been able to run this today on a 4090 (at vast) with the base sdxl model which was able to generate images at the resolution you specified.

I know that doesn't help much, but I don't believe it to be an issue with the installed software. If you can share your exact settings with models etc I can try again to force a failure.

**Comment by richbrownio** [comment]
Hi Rob - Thanks. Appologies for not getting back to you. I changed the upscaler and have just been creating at a lower resolution for the moment. The next time I jump into the VM at Vast I'll try to replicated the issue and send you the specifics. Thanks for your help.

**Comment by robballantyne** [comment]
Closing as stale but feel free to re-open if the issue persists
